POST https://ride-matching.herokuapp.com/api/v1/findDriver/Arose 
content-type: application/json

{
    "starting_point": {
        "lat": 31.442758,
        "lng": 74.267835
    },
    "ending_point": {
        "lat": 31.470940,
        "lng": 74.302191
    }
}